name: Run Pretests on Pull Requests
on:
    pull_request:
        branches:
        - master
        - dev
    push:
        branches:
        - master
        - dev
    
jobs:
    pretest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24'

            - name: Install dependencies
              run: npm install

            - name: Run pretests
              run: npm run pretest